# NOTE: The commented-out values with "REPLACE-ME" must be supplied via helm --set if not provided here
# Please don't commit them to version control.

invenio:
    init: true  # initiates db, index, and admin roles
    hostname: "icl-invenio-dev.uksouth.cloudapp.azure.com"
    #secret_key: "REPLACE-ME"
    #security_login_salt: "REPLACE-ME"
    #csrf_secret_salt: "REPLACE-ME"
    create_fixtures: true
    extraConfig:
      INVENIO_MAIL_SERVER: "smtp.office365.com"
      INVENIO_MAIL_PORT: "587"
      INVENIO_MAIL_USE_TLS: "True"
      INVENIO_SETTINGS_MODULE: "ic_data_repo.config.production"
      INVENIO_DATACITE_ENABLED: "True"
    #  ICL_OAUTH_CLIENT_ID: "REPLACE-ME"
    #  ICL_OAUTH_CLIENT_SECRET: "REPLACE-ME"
    #  ICL_OAUTH_WELL_KNOWN_URL: "REPLACE-ME"
    datacite:
      enabled: true
web:
  image: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
  resources:
    requests:
      cpu: 750m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
nginx:
  extra_server_config: |
    location /api/communities {
        limit_except GET OPTIONS {
            deny all;
        }
    }

worker:
  image: ""
  livenessProbe:
    initialDelaySeconds: 120

persistence:
  enabled: true
  storage_class: "azure-invenio-storage-class"

haproxy:
  enabled: false

flower:
  enabled: false

#rabbitmq:
#    auth:
#      password: "REPLACE-ME"

postgresql:
  enabled: false
#    auth:
#      password: "REPLACE-ME"

postgresqlExternal:
  databaseName: "invenio"
  username: "invenio"
  port: 5432

ingress:
  enabled: true
  class: "webapprouting.kubernetes.azure.com"
  tlsSecretNameOverride: "invenio-letsencrypt-secret"
  annotations:
    kubernetes.io/ingress.class: "webapprouting.kubernetes.azure.com"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: "50G"

clusterissuer:
  email: "sysadmin+icl@cottagelabs.com"

opensearch:
  data:
    resources:
      limits:
        cpu: 750m
        ephemeral-storage: 2Gi
        memory: 2Gi
      requests:
        cpu: 500m
        ephemeral-storage: 50Mi
        memory: 1.5Gi
