# NOTE: The commented-out values with "REPLACE-ME" must be supplied via helm --set if not provided here
# Please don't commit them to version control.

image:
  registry: ghcr.io/imperialcollegelondon
  repository: fair-data-repository

invenio:
  init: true # initiates db, index, and admin roles
  hostname: ""
  #secret_key: "REPLACE-ME"
  #security_login_salt: "REPLACE-ME"
  #csrf_secret_salt: "REPLACE-ME"
  create_fixtures: true
  extraConfig:
    INVENIO_MAIL_SERVER: "smtp.office365.com"
    INVENIO_MAIL_PORT: "587"
    INVENIO_MAIL_USE_TLS: "True"
    INVENIO_SETTINGS_MODULE: "ic_data_repo.config.production"
  #  ICL_OAUTH_CLIENT_ID: "REPLACE-ME"
  #  ICL_OAUTH_CLIENT_SECRET: "REPLACE-ME"
  #  ICL_OAUTH_WELL_KNOWN_URL: "REPLACE-ME"
  existingSecret: icl-secrets
  extra_secrets:
    icl_secrets:
      enabled: true
      secret_name: icl-secrets
    database_secrets:
      enabled: true
      secret_name: database-password-secrets
    rabbitmq_secrets:
      enabled: true
      secret_name: rabbitmq-password-secrets
  datacite:
    enabled: true
    existingSecret:
web:
  image: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 1
    exec:
      command:
        - /bin/bash
        - -c
        - '/opt/invenio/src/.venv/bin/uwsgi_curl -X HEAD -H ''Host: {{ include "invenio.hostname" $ }}'' $(hostname):5000 /ping'
  startupProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    exec:
      command:
        - /bin/bash
        - -c
        - '/opt/invenio/src/.venv/bin/uwsgi_curl -X HEAD -H ''Host: {{ include "invenio.hostname" $ }}'' $(hostname):5000 /ping'
  resources:
    requests:
      cpu: 750m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  initContainers:
    resources:
      requests:
        cpu: "1"
        memory: 100Mi
      limits:
        cpu: "1"
        memory: 100Mi
nginx:
  extraServerConfig: |
    location = /api/communities {
        limit_except GET OPTIONS {
            deny all;
        }
    }
    # Block all .map files in /static and /static/dist
    location ~ ^/static/.*\.map$ {
      deny all;
      return 403;
    }
    # Block access to /account/settings/applications/ and subpaths
    location ~ ^/account/settings/applications(/|$) {
        deny all;
    }
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 250m
      memory: 500Mi
worker:
  image: ""
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 360
    exec:
      command:
        - /bin/bash
        - -c
        - "/opt/invenio/src/.venv/bin/celery -A {{ .Values.worker.app }} inspect ping -d celery@$(hostname)"

workerBeat:
  livenessProbe:
    periodSeconds: 360
    exec:
      command:
        - /bin/bash
        - -c
        - "/opt/invenio/src/.venv/bin/celery -A {{ .Values.worker.app }} inspect ping"

persistence:
  enabled: true
  storage_class: "azure-invenio-storage-class"

haproxy:
  enabled: false

flower:
  enabled: false

#rabbitmq:
#    auth:
#      password: "REPLACE-ME"

postgresql:
  enabled: false
#    auth:
#      password: "REPLACE-ME"

postgresqlExternal:
  database: "invenio"
  username: "invenio"
  port: 5432
  existingSecret: database-password-secrets
  existingSecretPasswordKey: POSTGRES_PASSWORD

ingress:
  enabled: true
  tlsSecretNameOverride: "invenio-letsencrypt-secret"
  class: "azure/application-gateway"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"

clusterissuer:
  email: "sysadmin+icl@cottagelabs.com"

opensearch:
  data:
    resources:
      limits:
        cpu: 750m
        ephemeral-storage: 2Gi
        memory: 2Gi
      requests:
        cpu: 500m
        ephemeral-storage: 50Mi
        memory: 1.5Gi

redis:
  persistence:
    size: 8Gi
  master:
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 500Mi
  replica:
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 500Mi

rabbitmq:
  auth:
    existingPasswordSecret: rabbitmq-password-secrets
    existingSecretPasswordKey: RABBITMQ_PASSWORD
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 2Gi
