{{- if .Values.invenio.init }}
apiVersion: batch/v1
kind: Job
metadata:
  name: vocab-init
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
    app: vocab-init
    module: install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      containers:
      - name: vocab-init
        image: {{ required "Missing .Values.web.image" .Values.web.image }}
        command: [
          "/bin/bash",
          "-c",
          'python app_data/create_imperial_community.py && invenio shell --no-term-title -c ''from ic_data_repo.tasks import update_imperial_users, update_funders_vocabulary, import_full_affilations_vocab; update_funders_vocabulary.delay("https://zenodo.org/records/15475023/files/v1.66-2025-05-20-ror-data.zip?download=1"); import_full_affilations_vocab.delay()'''
        ]
        envFrom:
        - configMapRef:
            name: invenio-config
        env:
        - name: TZ
          value: {{ required "Missing .Values.global.timezone" .Values.global.timezone }}
        - name: INVENIO_BROKER_URL
          value: {{ include "invenio.rabbitmq.uri" . }}
        - name: INVENIO_CELERY_BROKER_URL
          value: {{ include "invenio.rabbitmq.uri" . }}
        - name: INVENIO_SQLALCHEMY_DATABASE_URI
          value: {{ include "invenio.sqlAlchemyDbUri" . }}
        - name: INVENIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: invenio-secrets
              key: INVENIO_SECRET_KEY
        - name: INVENIO_SECURITY_LOGIN_SALT
          valueFrom:
            secretKeyRef:
              name: invenio-secrets
              key: INVENIO_SECURITY_LOGIN_SALT
        - name: INVENIO_CSRF_SECRET_SALT
          valueFrom:
            secretKeyRef:
              name: invenio-secrets
              key: INVENIO_CSRF_SECRET_SALT
        volumeMounts:
          {{- range $key, $value := .Values.invenio.vocabularies }}
          - name: vocabularies
            mountPath: "/opt/invenio/var/instance/app_data/vocabularies/{{ $key }}"
            subPath: "{{ $key }}"
          {{- end }}
        {{- include "invenio.config.sentry" . | nindent 8 }}
        {{- if .Values.web.resources }}
        resources: {{- toYaml .Values.web.resources | nindent 10 }}
        {{- end }}
      restartPolicy: OnFailure
      {{- if .Values.invenio.vocabularies }}
      volumes:
        - name: vocabularies
          configMap:
            name: "invenio-vocabularies"
      {{- end }}
      {{- if .Values.web.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.web.imagePullSecret }}
      {{- end }}
{{- end }}
